### ISSUE TITLE
windows下安装问题

### ISSUE THREAD

**Issue by mlyknown** [jackhutu/jackblog-admin#1]
[15:08:13] Error in plugin 'gulp-compass'
Message:
    You need to have Ruby and Compass installed and in your system PATH for this task to work.

安装了ruby还是报这个错了，windows下这个插件有什么可以替代了吗？ 这个开发环境好复杂的感觉

**Comment by hutuxuhui** [comment]
这个主要是用到了sass, compass,  要说复杂也没什么,  如果是学习的话, 都是好东西. windows下估计主要是node-sass这个包难装.  如果你烦这个CSS预处理的话, 可以直接安装编译好的CSS `npm i jackblog-sass` , 然后修改一下gulp任务.  其实其它的版本web客户端, 为了方便安装我都去掉了sass处理.

**Comment by mlyknown** [comment]
node-sass 用cnpm安装是没问题的, 就是gulp-compass这个插件优点麻烦。。 修改一下gulp任务。这个怎么修改啊。我直接删了就报错了

**Comment by hutuxuhui** [comment]
你装好sass和compass的吗, 它们需要ruby 环境的, gulp-compass这个插件在windows是装不了吗? 还是装了还有问题, 如果装了还有问题, 那可能出在windows下compass处理雪碧图上, 注释掉[https://github.com/jackhutu/jackblog-admin/blob/master/src/app/!base.scss](https://github.com/jackhutu/jackblog-admin/blob/master/src/app/!base.scss) 第2到22行. 就可以不用处理图片了.

**Comment by mlyknown** [comment]
谢了。。 终于折腾好了,有问题再问~~
