### ISSUE TITLE
admin。3001端口前台请求的是9000端口

### ISSUE THREAD

**Issue by nonacosa** [jackhutu/jackblog-admin#2]
请求：GET http://localhost:9000/users/getCaptcha?0.37840757436362105 net::ERR_CONNECTION_REFUSED
类似这样的9000请求很多，应该是测试用的吧？
验证码也请求不到，请问我应该修改哪些配置？

**Comment by nonacosa** [comment]
不好意思搞懂了，忘记打包了，跟大家说明一下

**Comment by nonacosa** [comment]
最后问一下，你的github   qq登录应该目前都用不了了

去哪里注册账号？一直提示我账号密码错误

**Comment by hutuxuhui** [comment]
你是说jackhu.top博客上登录不了, 还是本机开发? 博客上可以登录啊. 账号密码只能管理员用户登录.

**Comment by nonacosa** [comment]
本地登录直接登录github账号然后去你的.top查看。直接到你的.top登录的是我的github账号了，

**Comment by hutuxuhui** [comment]
本机登录成功再到博客查看是无效的.
